### ISSUE TITLE
Multiple Sensors Running in Interrupt Example

### ISSUE THREAD

**Issue by JGarrett7** [stm32duino/X-NUCLEO-53L3A2#8]
It would be nice if the "HelloWorld_Interrupt" code worked with multiple sensors. It looks like it is close. It has a "SATELLITES_MOUNTED" definition and "begin" and "off" for the satellites, but only ever initializes, starts, and reads measurements for the "top" sensor.

**Comment by cparata** [comment]
Hello @JGarrett7 ,
we did not implement the interrupt code for multiple sensors because by default the interrupt pins for the satellites are not routed on the Arduino header. You must close some solder bridges to get the interrupt pins of the satellites routed on the connector. So, I prefer to avoid releasing a code that does not work out-of-the-box with the default hardware configuration of the shield. The reason why you find some code for the satellites in this example is because if you keep the satellites mounted, you must disable them using the xshut pins to get the sensor on board of the shield working properly in interrupt mode; otherwise you would have a hardware conflict. So, in this case you must uncomment the "SATELLITES_MOUNTED" define in the sketch. If you do not have the satellites mounted, you can keep the "SATELLITES_MOUNTED" define commented and everything should work without any issue.
Best Regards,
Carlo
